############
# Advanced #
############
editor nvim

###############
# Keybindings #
###############
map shift+right next_tab
map shift+left previous_tab
map ctrl+q close_tab

#################
# Look and Feel #
#################
background_opacity 0.60
font_size 12.0

########
# Tabs #
########
tab_bar_style                   custom
tab_separator                   ""
tab_fade                        0 0 0 0
tab_title_template              "{fmt.fg.default}{fmt.bg.default}  {index}: {title}{' []' if layout_name == 'stack' else ''} "
active_tab_title_template       "{fmt.fg._689d6a}{fmt.bg.default}  {index}: {title}{' []' if layout_name == 'stack' else ''} "
tab_bar_edge                    bottom
tab_bar_align                   left
tab_bar_margin_width            15.0
tab_bar_margin_height           10.0 0.0
active_tab_font_style           normal
inactive_tab_font_style         normal
tab_bar_min_tabs                2
tab_activity_symbol             none
bell_on_tab                     no

##########
# Cursor #
##########
cursor #689d6a 
cursor_shape beam

#####################
# Shell Integration #
#####################
shell_integration no-cursor


# BEGIN_KITTY_THEME
# Gruvbox Dark
include current-theme.conf
# END_KITTY_THEME


# BEGIN_KITTY_FONTS
font_family      family="JetBrainsMono Nerd Font"
bold_font        auto
italic_font      auto
bold_italic_font auto
# END_KITTY_FONTS
