add_newline = false
command_timeout = 200
format = "[$os$directory$git_branch$git_status]($style)$character"

[character]
error_symbol = "[✗](bold red)"
success_symbol = "[>](bold cyan)"

[os]
format = "[$symbol]($style)"
style = "bold cyan"
disabled = false

[os.symbols]
Arch = "󰣇 "
Macos = " "

[directory]
truncate_to_repo = false
truncation_length = 3
truncation_symbol = "…/"
before_repo_root_style = "bold cyan"
repo_root_style = "bold cyan"
repo_root_format = "[$before_root_path]($before_repo_root_style)[$repo_root]($repo_root_style)[$path]($style)[$read_only]($read_only_style) "

[git_branch]
format = "[$branch]($style) "
style = "italic cyan"

[git_status]
#format     = '[$all_status]($style)'
format = ''
style = "cyan"
ahead = "⇡${count} "
diverged = "⇕⇡${ahead_count}⇣${behind_count} "
behind = "⇣${count} "
conflicted = " "
up_to_date = " "
untracked = "? "
modified = " "
stashed = ""
staged = ""
renamed = ""
deleted = ""
